---
- name: Install Hyrax Prerequisites
  hosts: hyrax

  vars:
    appusername: hyrax
    rbenv_version: v1.1.1
    ruby_version: 2.4.4

  roles:
    - { name: ucsdlib.fits, version: 1.0.5, become: true }
    - { name: ucsdlib.libreoffice, become: true }
    - { name: ucsdlib.redis, become: true }
    - { name: zzet.rbenv,
        rbenv: {
          env: user,
          version: '{{ rbenv_version }}',
          default_ruby: '{{ ruby_version }}',
          rubies: [
            version: '{{ ruby_version }}'
          ]
        },
        rbenv_users: [
          '{{ appusername }}'
        ]
      }

  pre_tasks:
    - name: Create Hyrax App Group
      group:
        name: '{{ appusername }}'
        state: present
      become: true

    - name: Create Hyrax App User
      user:
        name: '{{ appusername }}'
        group: '{{ appusername }}'
        state: present
      become: true
